AppBundle\Entity\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        code:
            expose: true
            type: string
            groups: [Default]
        ean:
            expose: true
            type: string
        type:
            expose: true
            type: string
